package bundlemanagement.service;

public enum BundleOption {
	PACWITHPLATINUMCALLING, PACWITHGOLDCALLING, PACWITHSILVERCALLING, 
	PACWITHBRONZECALLING, PACWITHPLATINUMMESSAGING, PACWITHGOLDMESSAGING,
	PACWITHSILVERMESSAGING, PACWITHBRONZEMESSAGING, PACWITHPLATINUMDATA,
	PACWITHGOLDDATA, PACWITHSILVERDATA, PACWITHBRONZEDATA, PLAINPACBUNDLE,
	PLATINUM, SILVER, GOLD, BRONZE

}
