package bundlemanagement.service;

public enum BundleOption {
	PAC_WITH_PLATINUM_CALLING, PAC_WITH_GOLD_CALLING, PAC_WITH_SILVER_CALLING, 
	PAC_WITH_BRONZE_CALLING, PAC_WITH_PLATINUM_MESSAGING, PAC_WITH_GOLD_MESSAGING,
	PAC_WITH_SILVER_MESSAGING, PAC_WITH_BRONZE_MESSAGING, PAC_WITH_PLATINUM_DATA,
	PAC_WITH_GOLD_DATA, PAC_WITH_SILVER_DATA, PAC_WITH_BRONZE_DATA, PLAIN_PAC_BUNDLE,
	PLATINUM, SILVER, GOLD, BRONZE

}
